name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and test app workspace
        run: |
          if [ -f app/package.json ]; then
            cd app
            npm ci
            npm run lint --if-present
            npm run test --if-present -- --watch=false
            npm run build --if-present
          else
            echo "No app/package.json found; skipping Node workspace checks."
          fi
