name: CI

on:
  push:
    paths: ["app/**", ".github/workflows/ci.yml"]
  pull_request:
    paths: ["app/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json
      - name: Install (CI)
        run: npm ci
      - name: Lint
        run: npm run lint || echo "lint script not ready yet"
      - name: Test
        run: npm run test || echo "tests not ready yet"

