name: CI

on:
  push:
    paths: ["app/**", ".github/workflows/ci.yml"]
  pull_request:
    paths: ["app/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # remove cache settings for now (no lockfile present)

      - name: Use public npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install
        run: npm install --no-audit --no-fund

      - name: Lint
        run: npm run lint || echo "lint not set up yet"

      - name: Test
        run: npm run test || echo "tests not set up yet"
