name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build site artifact
        run: |
          set -e
          SITE_DIR="site"
          rm -rf "$SITE_DIR"
          mkdir -p "$SITE_DIR"

          if [ -f app/package.json ]; then
            cd app
            npm ci
            npm run build --if-present
            BUILD_DIR="dist"
            if [ -d "build" ]; then
              BUILD_DIR="build"
            fi
            cd ..
            if [ -d "app/$BUILD_DIR" ]; then
              cp -R app/$BUILD_DIR/. "$SITE_DIR"/
            else
              echo "Warning: Build directory '$BUILD_DIR' not found; skipping app artifact copy."
            fi
          else
            echo "No app/package.json found; using repository root static assets."
          fi

          # Include root static assets if present
          find . -maxdepth 1 -type f \( -name '*.html' -o -name 'CNAME' \) -exec cp {} "$SITE_DIR"/ \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
